title: "Panyi Dong"
author: "Panyi Dong"
description: "On developing..."
permalink: /:title/
lang: "en"
excerpt_separator: "\n\n\n"
date_format: "%B %d, %Y"

# Layout

show_excerpts: true        # show article excerpts on the home page
show_frame: true           # adds a gray frame to the site
show_sidebar: true        # show a sidebar instead of the usual header
minimal: false             # use a dark header

# Menu

navigation:                # accepts {file, title, url, icon, sidebaricon}
  - {file: "index.html", icon: home, title: Home}
  - {file: "repo.md", title: Reposity}
  - {file: "documentation.md", title: Documentation}
  - {file: "README.md", title: About Me}

external:                  # shows a footer with social links - for available icons see fontawesome.com/icons
  - {title: Mail, icon: envelope, url: "mailto:panyidong0@gmail.com"}
  - {title: Github, icon: github, url: "https://github.com/PanyiDong"}
  - {title: twitter, icon: twitter, url: "https://twitter.com/pydong0_0"}

comments:
#  disqus_shortname: ""    # see https://disqus.com/
#  isso_domain: ""         # see https://posativ.org/isso/

plugins:
 - jekyll-feed
 - jekyll-relative-links

relative_links:
  - enabled: true
  - collections: true
  
include:
 - repo.md
 - documentation.md
 - README.md
 - _documentation/parallel-computing/installation-and-intro-to-openmp.md
